# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"%\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\"-\n\x11\x43reateBookRequest\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book\"6\n\x12\x43reateBookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2N\n\x0b\x42ookService\x12?\n\nCreateBook\x12\x17.book.CreateBookRequest\x1a\x18.book.CreateBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=20
  _globals['_BOOK']._serialized_end=57
  _globals['_CREATEBOOKREQUEST']._serialized_start=59
  _globals['_CREATEBOOKREQUEST']._serialized_end=104
  _globals['_CREATEBOOKRESPONSE']._serialized_start=106
  _globals['_CREATEBOOKRESPONSE']._serialized_end=160
  _globals['_BOOKSERVICE']._serialized_start=162
  _globals['_BOOKSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
